"""Client-facing HTML readiness report — lightweight, no blob re-processing.

Operators share this with clients or attach it to an approval thread: a printable
checklist of scope, payment, signature, safety, and export risks with next steps.
"""

from __future__ import annotations

from html import escape

from docos.services.provenance.readiness import ReadinessReport

_STATUS_LABEL = {"pass": "Pass", "warn": "Review", "fail": "Fix before send"}
_VERDICT_HEADLINE = {
    "ready": "Ready to send",
    "needs_fixes": "Fix before sending",
    "blocked": "Blocked — do not send yet",
}


def render_readiness_html(
    *,
    title: str,
    doc_id: str,
    report: ReadinessReport,
) -> str:
    """Return a self-contained HTML document suitable for print / Save as PDF."""
    issues = [c for c in report.checks if c.status != "pass"]
    auto_fixes = [c for c in issues if c.fixable and c.fix_action]
    manual = [c for c in issues if not (c.fixable and c.fix_action)]

    rows = []
    for check in report.checks:
        badge = _STATUS_LABEL.get(check.status, check.status)
        badge_class = (
            "pass" if check.status == "pass" else "warn" if check.status == "warn" else "fail"
        )
        count = f' <span class="count">{check.count}</span>' if check.count else ""
        rows.append(
            f'<tr class="{badge_class}">'
            f"<td><strong>{escape(check.label)}</strong>{count}</td>"
            f'<td class="status">{escape(badge)}</td>'
            f"<td>{escape(check.detail)}</td>"
            "</tr>"
        )

    action_items: list[str] = []
    for check in auto_fixes:
        action_items.append(f"Run in DocOS: fix “{check.label}” ({check.detail})")
    for check in manual:
        action_items.append(f"Edit document: {check.label} — {check.detail}")

    actions_html = (
        "".join(f"<li>{escape(item)}</li>" for item in action_items)
        if action_items
        else "<li>No open issues — packet is send-ready.</li>"
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>{escape(title)} — Client Packet Readiness</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 820px; margin: 2rem auto;
      color: #0f172a; }}
    h1 {{ font-size: 1.35rem; margin-bottom: 0.25rem; }}
    .meta {{ color: #64748b; font-size: 0.85rem; margin-bottom: 1.5rem; }}
    .verdict {{ padding: 1rem 1.25rem; border-radius: 8px; margin-bottom: 1.5rem; }}
    .verdict.ready {{ background: #ecfdf5; border: 1px solid #a7f3d0; }}
    .verdict.needs_fixes {{ background: #fffbeb; border: 1px solid #fde68a; }}
    .verdict.blocked {{ background: #fef2f2; border: 1px solid #fecaca; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
    th, td {{ border: 1px solid #e2e8f0; padding: 0.55rem 0.65rem; vertical-align: top; }}
    th {{ background: #f8fafc; text-align: left; }}
    tr.pass td.status {{ color: #15803d; }}
    tr.warn td.status {{ color: #b45309; }}
    tr.fail td.status {{ color: #b91c1c; }}
    .count {{ background: #f1f5f9; border-radius: 999px; padding: 0 0.35rem; font-size: 0.75rem; }}
    h2 {{ font-size: 1rem; margin-top: 2rem; }}
    ol {{ line-height: 1.5; }}
    @media print {{ body {{ margin: 0.5in; }} }}
  </style>
</head>
<body>
  <h1>Client Packet Readiness Report</h1>
  <p class="meta">Document: {escape(title)} · ID {escape(doc_id)} · Generated by DocOS</p>
  <div class="verdict {escape(report.verdict)}">
    <strong>{escape(_VERDICT_HEADLINE.get(report.verdict, report.verdict))}</strong>
    <p>{escape(report.summary)}</p>
  </div>
  <table>
    <thead><tr><th>Check</th><th>Status</th><th>Detail</th></tr></thead>
    <tbody>{"".join(rows)}</tbody>
  </table>
  <h2>Recommended next steps</h2>
  <ol>{actions_html}</ol>
  <p class="meta">DocOS checks are deterministic and redaction-aware.
    Auto-fixes run as audited, reversible edits.</p>
</body>
</html>"""
